# Generated by Django 4.1.5 on 2023-03-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lugar', models.TextField(max_length=200)),
                ('Integrante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Integrante1', to='registroApp.persona')),
                ('Integrante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Integrante2', to='registroApp.persona')),
            ],
        ),
    ]
