# Generated by Django 4.1.5 on 2023-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fec_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fec_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fec_fundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Corto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=3)),
                ('fec_estreno', models.DateField()),
                ('idioma', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('sinopsis', models.TextField(max_length=50)),
                ('actua', models.ManyToManyField(to='vimad_app.actor')),
                ('dirige', models.ManyToManyField(to='vimad_app.director')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
