# Generated by Django 4.1.5 on 2023-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corto',
            name='produce',
            field=models.ManyToManyField(to='vimad_app.estudio'),
        ),
    ]
