# Generated by Django 4.1.5 on 2023-02-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0002_corto_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
