# Generated by Django 4.1.5 on 2023-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0003_estudio_votos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='votos',
        ),
        migrations.AddField(
            model_name='corto',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
