# Generated by Django 4.1.5 on 2023-02-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0005_question_remove_corto_votos_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='corto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cortos/'),
        ),
    ]
